version: "3.7"
##############################
# SERVICES
#
services:
  ######################
  # MONITORING
  #
  ##########
  # Node Exporter - Prometheus exporter for hardware and OS metrics exposed by *NIX kernels
  #
  node_exporter:
    image: prom/node-exporter:${NODE_EXPORTER_TAG}
    container_name: nodeexporter
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    environment:
      TZ: ${TZ}
    labels:
      org.label-schema.group: "monitoring"
  #
  ##########
  
  ##########
  # cAdvisor - nalyzes and exposes resource usage and performance data from running containers.
  #
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:${CADVISOR_TAG}
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    security_opt:
      - no-new-privileges:true
    network_mode: host
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /volume3/@docker:/var/lib/docker:ro
    # - /cgroup:/cgroup:ro
    environment:
      TZ: ${TZ}
    labels:
      org.label-schema.group: "monitoring"
  #
  ##########
  #
  ####################
#
##############################
