global:
  scrape_interval: 15s # How frequently to scrape targets by default. | default = 1m 
  # scrape_timeout: 10s # How long until a scrape request times out. | default = 10s
  # evaluation_interval: 1m # How frequently to evaluate rules. | default = 1m

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    prometheus: monitor
    domain: home.hessenflow.net
  # File to which PromQL queries are logged.
  # Reloading the configuration will reopen the file.
  # Load and evaluate rules in this file every 'evaluation_interval' seconds.
  # query_log_file: logs/query.log

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
# rule_files:
rule_files:
  - "alert.rules"
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

# A list of scrape configurations.
scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['catacomb:9100']
      - targets: ['unity:9100']
    
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['catacomb:8080']
    
  # - job_name: caddy
    # static_configs:
      # - targets: ['caddy:2019']
  
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  
  # - job_name: 'grafana_metrics'
    # scrape_interval: 15s
    # static_configs:
      # - targets: ['grafana:3000']
